import { Link, useNavigate } from "react-router-dom";
import servicesOne from "../assets/pexels-photo-238480.jpeg";
import BorderImage from "../assets/services.png";
import { useEffect } from "react";

function Brand() {
  const user = localStorage.getItem("user");
  const userAuth = JSON.parse(user);
  const navigate = useNavigate();

  useEffect(() => {
    if (userAuth?.userToken) {
      navigate("/");
    } else {
      navigate("/brand");
    }
  }, [userAuth, navigate]);
  return (
    <>
      <section className="bg-brand relative">
        <div className="relative bg-gradient-to-t from-[#0000003d] to-[#000000a1] w-full h-[60vh] md:h-[70vh] flex items-center flex-col gap-5 pt-32 md:pt-40">
          <div className="flex flex-col justify-center items-center gap-3 md:gap-5">
            <h2 className="text-lg text-white font-bold uppercase md:text-4xl">
              YOU ARE A BRAND?
            </h2>
            <h2 className="text-[#ffc670] text-2xl font-bold md:text-5xl">
              DISCOVER THE PERFECT MATCH
            </h2>
            <h3 className="text-[#fff] text-sm leading-6 w-[90%] font-normal md:text-lg md:w-[54%] text-center">
              The purpose is to leverage the power of social media by linking
              our exclusive database of influencers and models with lifestyle
              brands and F&B, hospitality, entertainment and wellness venues to
              create a unique and unconventional marketing opportunity.
            </h3>
            <Link
              to="/brand-contract"
              className="bg-[#cfa361] w-40 md:w-52 text-center py-2 text-white font-bold text-base rounded-full hover:bg-white hover:text-black transition-all hover:w-56 mt-5 md:text-2xl"
            >
              Join Us <i className="fa-regular fa-paper-plane"></i>
            </Link>
          </div>
        </div>
      </section>
      <section className="mt-[-100px] relative">
        <div className="container py-10">
          <div className="grid grid-cols-1 lg:grid-cols-4 md:grid-cols-2 gap-5">
            <div className="flex flex-col gap-2 items-center justify-center p-8 border-t-8 border border-[#DEA23A] bg-white md:px-4">
              <i className="fas fa-money-bill-wave text-[#DEA23A] text-[60px]"></i>
              <h2 className="text-[#2a2a2a] text-base font-bold mt-5 md:text-xl uppercase">
                10x LESS
              </h2>
              <p className="text-base font-normal text-black text-center">
                10x LESS EXPENSIVE THAN AN AGENCY
              </p>
            </div>
            <div className="flex flex-col gap-2 items-center justify-center p-8 border-t-8 border border-[#DEA23A] bg-white md:px-4">
              <i className="far fa-clock text-[#DEA23A] text-[60px]"></i>
              <h2 className="text-[#2a2a2a] text-base font-bold mt-5 md:text-xl uppercase">
                NO WASTE OF TIME
              </h2>
              <p className="text-base font-normal text-black text-center">
                TO MANAGE YOUR INFLUENCE DIGITAL MARKETING
              </p>
            </div>
            <div className="flex flex-col gap-2 items-center justify-center p-8 border-t-8 border border-[#DEA23A] bg-white md:px-4">
              <i className="fas fa-film text-[#DEA23A] text-[60px]"></i>
              <h2 className="text-[#2a2a2a] text-base font-bold mt-5 md:text-xl uppercase">
                ON AVERAGE
              </h2>
              <p className="text-base font-normal text-black text-center">
                20 MORE CLIENTS GENERATED BY EVERY INFLUENCER
              </p>
            </div>
            <div className="flex flex-col gap-2 items-center justify-center p-8 border-t-8 border border-[#DEA23A] bg-white md:px-4">
              <i className="fas fa-users text-[#DEA23A] text-[60px]"></i>
              <h2 className="text-[#2a2a2a] text-base font-bold mt-5 md:text-xl uppercase">
                WELL QUALIFIED
              </h2>
              <p className="text-base font-normal text-black text-center">
                A WELL QUALIFIED INFLUENCER COMMUNITY OFFERED
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-[#F8F8F8] py-10">
        <div className="container">
          <h2 className="text-black text-2xl font-bold uppercase text-center">
            OUR SERVICES
          </h2>
          <img src={BorderImage} alt="" className="m-auto" />
          <div className="py-14 px-2 grid grid-cols-1 gap-5 lg:grid-cols-3 md:grid-cols-2">
            <div className="bg-white rounded-lg shadow-xl flex flex-col gap-5">
              <img
                src={servicesOne}
                alt=""
                className="w-full h-72 rounded-t-xl"
              />
              <h2 className="text-[#cfa361] text-2xl font-bold text-center">
                Influence Strategy
              </h2>
              <p className="text-base font-normal text-center px-5 pb-5">
                Our E-RP experts know the ROI of each influencer and optimize
                your campaigns as much as possible through product placements,
                launch parties, contests or even white label collaborations.
              </p>
            </div>
            <div className="bg-white rounded-lg shadow-xl flex flex-col gap-5">
              <img
                src={servicesOne}
                alt=""
                className="w-full h-72 rounded-t-xl"
              />
              <h2 className="text-[#cfa361] text-2xl font-bold text-center">
                Community Management
              </h2>
              <p className="text-base font-normal text-center px-5 pb-5">
                We help you get more followers and a better engagement rate with
                more likes and comments. We boost your growth through a unique
                strategy created and implemented by our social media experts
              </p>
            </div>
            <div className="bg-white rounded-lg shadow-xl flex flex-col gap-5">
              <img
                src={servicesOne}
                alt=""
                className="w-full h-72 rounded-t-xl"
              />
              <h2 className="text-[#cfa361] text-2xl font-bold text-center">
                Content Creation
              </h2>
              <p className="text-base font-normal text-center px-5 pb-5">
                Our production team was recruited after long castings and hiring
                processes to bring together the most creative and technical
                talents. Become stronger thanks to a tailor-made digital
                identity.
              </p>
            </div>
            <div className="bg-white rounded-lg shadow-xl flex flex-col gap-5">
              <img
                src={servicesOne}
                alt=""
                className="w-full h-72 rounded-t-xl"
              />
              <h2 className="text-[#cfa361] text-2xl font-bold text-center">
                Branding
              </h2>
              <p className="text-base font-normal text-center px-5 pb-5">
                Are you launching a new brand? Does your brand image no longer
                suit you? We take care of everything! Logo, graphic charter,
                naming, slogan, our team comes together around your concept and
                together creates a powerful DNA.
              </p>
            </div>
            <div className="bg-white rounded-lg shadow-xl flex flex-col gap-5">
              <img
                src={servicesOne}
                alt=""
                className="w-full h-72 rounded-t-xl"
              />
              <h2 className="text-[#cfa361] text-2xl font-bold text-center">
                Website Design
              </h2>
              <p className="text-base font-normal text-center px-5 pb-5">
                From a showcase site to an e-shop, from design to maintenance,
                our team of developers offers you a turnkey solution to attract
                and convert more customers through an optimized website. It’s
                time to strengthen your online presence and increase your
                turnover!
              </p>
            </div>
            <div className="bg-white rounded-lg shadow-xl flex flex-col gap-5">
              <img
                src={servicesOne}
                alt=""
                className="w-full h-72 rounded-t-xl"
              />
              <h2 className="text-[#cfa361] text-2xl font-bold text-center">
                Sponsorship
              </h2>
              <p className="text-base font-normal text-center px-5 pb-5">
                Our Ads experts carry out acquisition and conversion campaigns
                to increase your turnover very quickly thanks to Facebook &
                Instagram advertising. From AB testing to retargeting, our team
                optimally uses the best techniques on the market for
                unprecedented results!
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export default Brand;
